name=RCControl
version=2.0.0
author=Karl Smirthwaite <nqn524@york.ac.uk>
maintainer=Karl Smirthwaite <nqn524@york.ac.uk>
sentence=Provides an easy way to connect a joystick 
paragraph=Also can do buttons
category=Communication
url=https://github.com/nqn524/WebAppControl
architectures=mbed_nano,esp32
includes=RCControl.h
depends=ArduinoBLE